In [1]:
import pandas as pd
import numpy as np
import matplotlib as mtl
import seaborn as sb
!pip install ydata-profiling

Looking in indexes: https://nexus.iisys.de/repository/ki-awz-pypi-group/simple, https://pypi.org/simple
Requirement already satisfied: ydata-profiling in /opt/conda/lib/python3.12/site-packages (4.18.1)
Requirement already satisfied: scipy<1.17,>=1.8 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (1.16.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (2.3.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (2.11.7)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /opt/conda/lib/python3.12/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (2.2.6)
Requirement already satisfied: minify-html>=0.15.0 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=4 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (0.61.2)
Requirement already satisfied: PyWavelets in /opt/conda/lib/python3.12/site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /opt/conda/lib/python3.12/site-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /opt/conda/lib/python3.12/site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /opt/conda/lib/python3.12/site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.2)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3,>=2->ydata-profiling) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.8.3)
Requirement already satisfied: patsy>=0.5.6 in /opt/conda/lib/python3.12/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /opt/conda/lib/python3.12/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /opt/conda/lib/python3.12/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Requirement already satisfied: puremagic in /opt/conda/lib/python3.12/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [29]:
df = pd.read_csv("dataset/attack/Attacks_V1_02-03-2026.csv",sep=';', low_memory=False)

In [31]:
df.shape

(996339, 52)

In [32]:
df.columns

Index(['id', 'headache', 'migraine', 'attack_time', 'intensity', 'duration',
       'symptoms_both_side_headache', 'symptoms_one_side_headache',
       'symptoms_pulsating_headache', 'symptoms_dull_headache',
       'symptoms_increased_during_physical_activity', 'symptoms_nausea',
       'symptoms_vomiting', 'symptoms_light_sensitivity',
       'symptoms_noise_sensitivity', 'symptoms_smell_sensitivity',
       'symptoms_vertigo', 'symptoms_concentration_disorder',
       'symptoms_tiredness', 'symptoms_aura', 'symptoms_aura_vision',
       'symptoms_aura_emotion', 'symptoms_aura_speech',
       'symptoms_aura_paralysis', 'effects_unfit_for_work',
       'effects_unfit_for_household_recreation', 'effects_doctor',
       'effects_emergency_room', 'effects_hospital', 'comment_menstruation',
       'patient_info_id', 'source_version_id', 'api_version_id', 'create_date',
       'modified_date', 'nMed', 'Triptane_Geb', 'Triptane_Eff',
       'EinfacheSM_Geb', 'EinfacheSM_Eff', 'Uebelkeit_Geb', 'Uebelkeit_Eff',
       'Opoide_Geb', 'Opoide_Eff', 'Kombi_Geb', 'Kombi_Eff',
       'DitaneGepante_Geb', 'DitaneGepante_Eff', 'Ergotamin_Geb',
       'Ergotamin_Eff', 'medication', 'weekday'],
      dtype='object')

In [33]:
df.head(10)

,id,headache,migraine,attack_time,intensity,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,...,Opoide_Geb,Opoide_Eff,Kombi_Geb,Kombi_Eff,DitaneGepante_Geb,DitaneGepante_Eff,Ergotamin_Geb,Ergotamin_Eff,medication,weekday
0,124,True,True,2020-06-25,8,360,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Donnerstag
1,125,True,True,2020-06-26,5,180,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Freitag
2,135,True,True,2020-06-27,3,240,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Samstag
3,172,True,True,2020-06-29,3,120,False,True,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Montag
4,179,True,False,2020-06-30,5,360,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Dienstag
5,186,True,True,2020-07-01,3,60,False,True,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Mittwoch
6,189,True,False,2020-07-01,5,420,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Mittwoch
7,194,True,False,2020-07-02,5,300,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Donnerstag
8,199,True,True,2020-07-02,2,60,False,True,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Donnerstag
9,215,True,False,2020-07-03,3,1440,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Freitag

In [7]:
from ydata_profiling import ProfileReport
report = ProfileReport(df, title="Post-Merge Profile", explorative=True)
report.to_file("profile_report_A1.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/52 [00:07<?, ?it/s]

KeyboardInterrupt

In [6]:
df['duration'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 996339 entries, 0 to 996338
Series name: duration
Non-Null Count   Dtype
--------------   -----
996339 non-null  int64
dtypes: int64(1)
memory usage: 7.6 MB

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.groupby(["patient_info_id"]).size().sort_values(ascending=False)

patient_info_id
25124162    1906
79404720    1837
78562347    1787
23072369    1771
79983539    1737
            ...
31311553       1
89021324       1
77463559       1
19911589       1
99519741       1
Length: 5401, dtype: int64

In [57]:
relevant_columns=["id","patient_info_id","headache","migraine","attack_time","duration","symptoms_both_side_headache", "symptoms_one_side_headache",
       "symptoms_pulsating_headache", "symptoms_dull_headache","weekday"]
req_df=df[relevant_columns].copy()

In [58]:
req_df.dtypes
#attack time is object need to change it
#weekday is also object needto change it maybe some kind of encoding

id                              int64
patient_info_id                 int64
headache                         bool
migraine                         bool
attack_time                    object
duration                        int64
symptoms_both_side_headache      bool
symptoms_one_side_headache       bool
symptoms_pulsating_headache      bool
symptoms_dull_headache           bool
weekday                        object
dtype: object

In [59]:
req_df["attack_time"] = pd.to_datetime(req_df["attack_time"])
req_df["weekday"].unique()

array(['Donnerstag', 'Freitag', 'Samstag', 'Montag', 'Dienstag',
       'Mittwoch', 'Sonntag'], dtype=object)

In [60]:
order = ["Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag","Sonntag"]
req_df["weekday"] = pd.Categorical(req_df["weekday"], categories=order, ordered=True)
req_df.dtypes

id                                      int64
patient_info_id                         int64
headache                                 bool
migraine                                 bool
attack_time                    datetime64[ns]
duration                                int64
symptoms_both_side_headache              bool
symptoms_one_side_headache               bool
symptoms_pulsating_headache              bool
symptoms_dull_headache                   bool
weekday                              category
dtype: object

In [61]:
req_df.head(5)

,id,patient_info_id,headache,migraine,attack_time,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,weekday
0,124,94719087,True,True,2020-06-25,360,False,True,True,False,Donnerstag
1,125,94719087,True,True,2020-06-26,180,False,True,True,False,Freitag
2,135,94719087,True,True,2020-06-27,240,False,True,True,False,Samstag
3,172,94719087,True,True,2020-06-29,120,False,True,False,False,Montag
4,179,70854341,True,False,2020-06-30,360,False,False,False,False,Dienstag

In [62]:
# Count missing values in each column
print(req_df.isnull().sum())

id                             0
patient_info_id                0
headache                       0
migraine                       0
attack_time                    0
duration                       0
symptoms_both_side_headache    0
symptoms_one_side_headache     0
symptoms_pulsating_headache    0
symptoms_dull_headache         0
weekday                        0
dtype: int64

In [63]:
print(req_df.isna().any())

id                             False
patient_info_id                False
headache                       False
migraine                       False
attack_time                    False
duration                       False
symptoms_both_side_headache    False
symptoms_one_side_headache     False
symptoms_pulsating_headache    False
symptoms_dull_headache         False
weekday                        False
dtype: bool

req_df.shape

In [64]:
#shape is 996339 * 10
req_df['id'].nunique()

996339

In [65]:
req_df = req_df.sort_values(["patient_info_id", "attack_time"])
req_df.head(5)

,id,patient_info_id,headache,migraine,attack_time,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,weekday
265160,1734884,10007520,True,False,2023-06-21,900,True,False,True,False,Mittwoch
266184,1744944,10007520,True,False,2023-06-24,300,True,False,True,False,Samstag
266823,1750577,10007520,True,False,2023-06-25,480,True,False,True,False,Sonntag
267168,1753437,10007520,True,False,2023-06-26,300,True,False,True,False,Montag
267693,1757973,10007520,True,False,2023-06-27,900,True,False,True,True,Dienstag

In [66]:
req_df.set_index("id")

,patient_info_id,headache,migraine,attack_time,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,weekday
id,,,,,,,,,,
1734884,10007520,True,False,2023-06-21,900,True,False,True,False,Mittwoch
1744944,10007520,True,False,2023-06-24,300,True,False,True,False,Samstag
1750577,10007520,True,False,2023-06-25,480,True,False,True,False,Sonntag
1753437,10007520,True,False,2023-06-26,300,True,False,True,False,Montag
1757973,10007520,True,False,2023-06-27,900,True,False,True,True,Dienstag
...,...,...,...,...,...,...,...,...,...,...
9250131,99991933,True,True,2025-09-03,1440,False,True,True,False,Mittwoch
9250161,99991933,True,False,2025-09-04,1440,True,False,False,True,Donnerstag
9273119,99991933,True,True,2025-09-05,1440,False,True,True,False,Freitag
9273127,99991933,True,True,2025-09-06,1440,False,True,True,False,Samstag
9273134,99991933,True,True,2025-09-07,1440,False,False,True,False,Sonntag

In [67]:
#check the numeric columns for irregularity

# Convert to numeric, invalid entries become NaN
req_df["duration_check"] = pd.to_numeric(req_df["duration"], errors='coerce')

# Rows where conversion failed
invalid_rows = req_df[req_df["duration_check"].isna()]
print("Rows with invalid duration values:")
print(invalid_rows)

Rows with invalid duration values:
Empty DataFrame
Columns: [id, patient_info_id, headache, migraine, attack_time, duration, symptoms_both_side_headache, symptoms_one_side_headache, symptoms_pulsating_headache, symptoms_dull_headache, weekday, duration_check]
Index: []

In [68]:
invalid_weekday = req_df[~req_df["weekday"].apply(lambda x: isinstance(x, str))]
print("Rows with non-string weekday:")
print(invalid_weekday)

Rows with non-string weekday:
Empty DataFrame
Columns: [id, patient_info_id, headache, migraine, attack_time, duration, symptoms_both_side_headache, symptoms_one_side_headache, symptoms_pulsating_headache, symptoms_dull_headache, weekday, duration_check]
Index: []

In [69]:
req_df.nunique()

id                             996339
patient_info_id                  5401
headache                            1
migraine                            2
attack_time                      2062
duration                           24
symptoms_both_side_headache         2
symptoms_one_side_headache          2
symptoms_pulsating_headache         2
symptoms_dull_headache              2
weekday                             7
duration_check                     24
dtype: int64

In [18]:
req_df[req_df["patient_info_id"] == 25124162].sort_values("attack_time")

,id,patient_info_id,headache,attack_time,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,weekday
37,425,25124162,True,2020-07-07,540,False,True,False,False,Dienstag
38,426,25124162,True,2020-07-08,360,False,True,False,False,Mittwoch
39,427,25124162,True,2020-07-09,360,False,True,False,False,Donnerstag
40,428,25124162,True,2020-07-10,840,False,True,False,False,Freitag
41,429,25124162,True,2020-07-11,60,False,True,False,False,Samstag
...,...,...,...,...,...,...,...,...,...,...
994634,11715336,25124162,True,2026-02-11,1440,False,False,False,False,Mittwoch
994635,11715340,25124162,True,2026-02-12,1440,False,False,False,False,Donnerstag
994636,11715346,25124162,True,2026-02-13,1440,False,False,False,False,Freitag
994637,11715351,25124162,True,2026-02-14,1440,False,False,False,False,Samstag
994638,11715356,25124162,True,2026-02-15,1440,False,False,False,False,Sonntag