In [1]:
import pandas as pd
import numpy as np
import matplotlib as mtl
import seaborn as sb

In [28]:
df = pd.read_csv("dataset/attack/Attacks_V4_02-03-2026.csv", on_bad_lines='warn', sep=';', low_memory=False)

In [21]:
df.shape

(428527, 52)

In [22]:
df.columns

Index(['id', 'headache', 'migraine', 'attack_time', 'intensity', 'duration',
       'symptoms_both_side_headache', 'symptoms_one_side_headache',
       'symptoms_pulsating_headache', 'symptoms_dull_headache',
       'symptoms_increased_during_physical_activity', 'symptoms_nausea',
       'symptoms_vomiting', 'symptoms_light_sensitivity',
       'symptoms_noise_sensitivity', 'symptoms_smell_sensitivity',
       'symptoms_vertigo', 'symptoms_concentration_disorder',
       'symptoms_tiredness', 'symptoms_aura', 'symptoms_aura_vision',
       'symptoms_aura_emotion', 'symptoms_aura_speech',
       'symptoms_aura_paralysis', 'effects_unfit_for_work',
       'effects_unfit_for_household_recreation', 'effects_doctor',
       'effects_emergency_room', 'effects_hospital', 'comment_menstruation',
       'patient_info_id', 'source_version_id', 'api_version_id', 'create_date',
       'modified_date', 'nMed', 'Triptane_Geb', 'Triptane_Eff',
       'EinfacheSM_Geb', 'EinfacheSM_Eff', 'Uebelkeit_Geb', 'Uebelkeit_Eff',
       'Opoide_Geb', 'Opoide_Eff', 'Kombi_Geb', 'Kombi_Eff',
       'DitaneGepante_Geb', 'DitaneGepante_Eff', 'Ergotamin_Geb',
       'Ergotamin_Eff', 'medication', 'weekday'],
      dtype='object')

In [23]:
df.head(50)

,id,headache,migraine,attack_time,intensity,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,...,Opoide_Geb,Opoide_Eff,Kombi_Geb,Kombi_Eff,DitaneGepante_Geb,DitaneGepante_Eff,Ergotamin_Geb,Ergotamin_Eff,medication,weekday
0,124,True,True,2020-06-25,8,360,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Donnerstag
1,125,True,True,2020-06-26,5,180,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Freitag
2,135,True,True,2020-06-27,3,240,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Samstag
3,172,True,True,2020-06-29,3,120,False,True,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Montag
4,186,True,True,2020-07-01,3,60,False,True,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Mittwoch
5,199,True,True,2020-07-02,2,60,False,True,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Donnerstag
6,224,True,True,2020-07-04,5,300,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Samstag
7,242,True,True,2020-07-05,3,120,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Sonntag
8,274,True,True,2020-07-07,3,120,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Dienstag
9,328,True,True,2020-07-09,4,240,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Donnerstag
10,361,True,False,2020-07-08,8,360,False,True,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Mittwoch
11,362,True,True,2020-07-09,6,300,False,True,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Donnerstag
12,363,True,True,2020-07-10,6,240,False,True,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Freitag
13,390,True,True,2020-07-11,3,120,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Samstag
14,401,True,True,2020-07-12,2,120,False,True,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Sonntag
15,425,True,False,2020-07-07,2,540,False,True,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Dienstag
16,426,True,False,2020-07-08,2,360,False,True,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Mittwoch
17,427,True,False,2020-07-09,2,360,False,True,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Donnerstag
18,428,True,True,2020-07-10,4,840,False,True,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Freitag
19,429,True,False,2020-07-11,0,60,False,True,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Samstag
20,430,True,False,2020-07-12,4,420,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Sonntag
21,440,True,True,2020-07-13,4,120,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Montag
22,488,True,True,2020-07-14,5,180,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Dienstag
23,508,True,False,2020-07-14,2,720,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Dienstag
24,509,True,False,2020-07-15,2,540,False,True,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Mittwoch
25,521,True,True,2020-07-15,3,120,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Mittwoch
26,532,True,False,2020-07-16,1,240,False,True,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Donnerstag
27,553,True,True,2020-07-12,8,1440,False,False,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Sonntag
28,554,True,True,2020-07-13,5,1440,False,False,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Montag
29,555,True,False,2020-07-14,5,720,False,False,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Dienstag
30,556,True,False,2020-07-15,6,960,False,False,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Mittwoch
31,557,True,False,2020-07-16,6,900,False,False,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Donnerstag
32,582,True,True,2020-07-16,3,180,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Donnerstag
33,583,True,True,2020-07-17,6,360,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Freitag
34,587,True,True,2020-07-17,7,1080,False,False,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Freitag
35,618,True,True,2020-07-18,5,900,False,False,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Samstag
36,639,True,False,2020-07-19,2,540,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Sonntag
37,641,True,False,2020-07-09,1,600,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Donnerstag
38,647,True,False,2020-07-11,2,960,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Samstag
39,649,True,False,2020-07-13,1,600,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Montag
40,664,True,False,2020-07-13,2,1440,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Montag
41,665,True,False,2020-07-14,2,1440,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Dienstag
42,666,True,False,2020-07-15,3,1440,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Mittwoch
43,667,True,False,2020-07-16,2,720,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Donnerstag
44,668,True,False,2020-07-17,2,720,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Freitag
45,669,True,False,2020-07-18,3,600,False,False,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Samstag
46,670,True,False,2020-07-19,1,600,False,True,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Sonntag
47,687,True,True,2020-07-19,4,180,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Sonntag
48,689,True,True,2020-07-19,6,960,False,False,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Sonntag
49,690,True,True,2020-07-20,6,780,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,0.0,True,Montag

In [24]:
df.duplicated().sum()

df.groupby(["patient_info_id"]).size().sort_values(ascending=False)

patient_info_id
25124162    1906
23072369    1771
77473155    1719
95697268    1697
56863116    1683
            ...
61193125       3
45377547       3
54881625       1
47908022       1
74853419       1
Length: 1333, dtype: int64

In [25]:
relevant_columns=["id","patient_info_id","headache","attack_time","duration","symptoms_both_side_headache", "symptoms_one_side_headache",
       "symptoms_pulsating_headache", "symptoms_dull_headache","weekday"]
req_df=df[relevant_columns]
req_df.head(50)

,id,patient_info_id,headache,attack_time,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,weekday
0,124,94719087,True,2020-06-25,360,False,True,True,False,Donnerstag
1,125,94719087,True,2020-06-26,180,False,True,True,False,Freitag
2,135,94719087,True,2020-06-27,240,False,True,True,False,Samstag
3,172,94719087,True,2020-06-29,120,False,True,False,False,Montag
4,186,94719087,True,2020-07-01,60,False,True,False,False,Mittwoch
5,199,94719087,True,2020-07-02,60,False,True,False,False,Donnerstag
6,224,94719087,True,2020-07-04,300,False,True,True,False,Samstag
7,242,94719087,True,2020-07-05,120,False,True,True,False,Sonntag
8,274,94719087,True,2020-07-07,120,False,True,True,False,Dienstag
9,328,94719087,True,2020-07-09,240,False,True,True,False,Donnerstag
10,361,57445154,True,2020-07-08,360,False,True,False,False,Mittwoch
11,362,57445154,True,2020-07-09,300,False,True,False,False,Donnerstag
12,363,57445154,True,2020-07-10,240,False,True,False,False,Freitag
13,390,94719087,True,2020-07-11,120,False,True,True,False,Samstag
14,401,94719087,True,2020-07-12,120,False,True,False,False,Sonntag
15,425,25124162,True,2020-07-07,540,False,True,False,False,Dienstag
16,426,25124162,True,2020-07-08,360,False,True,False,False,Mittwoch
17,427,25124162,True,2020-07-09,360,False,True,False,False,Donnerstag
18,428,25124162,True,2020-07-10,840,False,True,False,False,Freitag
19,429,25124162,True,2020-07-11,60,False,True,False,False,Samstag
20,430,25124162,True,2020-07-12,420,False,True,True,False,Sonntag
21,440,94719087,True,2020-07-13,120,False,True,True,False,Montag
22,488,94719087,True,2020-07-14,180,False,True,True,False,Dienstag
23,508,20992386,True,2020-07-14,720,False,False,False,False,Dienstag
24,509,20992386,True,2020-07-15,540,False,True,True,False,Mittwoch
25,521,94719087,True,2020-07-15,120,False,True,True,False,Mittwoch
26,532,20992386,True,2020-07-16,240,False,True,False,False,Donnerstag
27,553,27586093,True,2020-07-12,1440,False,False,True,False,Sonntag
28,554,27586093,True,2020-07-13,1440,False,False,False,False,Montag
29,555,27586093,True,2020-07-14,720,False,False,False,False,Dienstag
30,556,27586093,True,2020-07-15,960,False,False,False,False,Mittwoch
31,557,27586093,True,2020-07-16,900,False,False,False,False,Donnerstag
32,582,94719087,True,2020-07-16,180,False,True,True,False,Donnerstag
33,583,94719087,True,2020-07-17,360,False,True,True,False,Freitag
34,587,27586093,True,2020-07-17,1080,False,False,False,False,Freitag
35,618,27586093,True,2020-07-18,900,False,False,False,False,Samstag
36,639,20992386,True,2020-07-19,540,False,False,False,False,Sonntag
37,641,20992386,True,2020-07-09,600,False,False,False,False,Donnerstag
38,647,20992386,True,2020-07-11,960,False,False,False,False,Samstag
39,649,20992386,True,2020-07-13,600,False,False,False,False,Montag
40,664,25124162,True,2020-07-13,1440,False,False,False,False,Montag
41,665,25124162,True,2020-07-14,1440,False,False,False,False,Dienstag
42,666,25124162,True,2020-07-15,1440,False,False,False,False,Mittwoch
43,667,25124162,True,2020-07-16,720,False,False,False,False,Donnerstag
44,668,25124162,True,2020-07-17,720,False,False,False,False,Freitag
45,669,25124162,True,2020-07-18,600,False,False,True,False,Samstag
46,670,25124162,True,2020-07-19,600,False,True,False,False,Sonntag
47,687,94719087,True,2020-07-19,180,False,True,True,False,Sonntag
48,689,27586093,True,2020-07-19,960,False,False,True,False,Sonntag
49,690,27586093,True,2020-07-20,780,False,True,True,False,Montag

In [26]:
req_df = req_df.sort_values(["patient_info_id", "attack_time"])
req_df.head(50)

,id,patient_info_id,headache,attack_time,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,weekday
148731,2134807,10076484,True,2023-09-01,300,False,True,True,False,Freitag
148732,2134809,10076484,True,2023-09-02,1440,False,True,False,False,Samstag
148733,2134812,10076484,True,2023-09-03,1440,False,True,True,False,Sonntag
148734,2134814,10076484,True,2023-09-04,1440,False,True,True,False,Montag
148736,2134816,10076484,True,2023-09-05,1440,False,True,True,False,Dienstag
148737,2134817,10076484,True,2023-09-06,1440,False,True,True,False,Mittwoch
148738,2134821,10076484,True,2023-09-07,240,False,True,True,False,Donnerstag
148739,2134824,10076484,True,2023-09-08,900,False,True,True,False,Freitag
148740,2134828,10076484,True,2023-09-09,1440,False,True,True,False,Samstag
148741,2134830,10076484,True,2023-09-10,1440,False,True,True,False,Sonntag
148742,2134831,10076484,True,2023-09-11,1440,False,True,True,False,Montag
148743,2134833,10076484,True,2023-09-12,1440,False,True,True,False,Dienstag
148744,2134834,10076484,True,2023-09-13,1440,False,True,True,False,Mittwoch
148745,2134839,10076484,True,2023-09-14,1440,False,True,True,False,Donnerstag
148714,2134538,10076484,True,2023-09-15,1440,False,True,True,False,Freitag
149066,2141567,10076484,True,2023-09-16,1440,False,True,True,False,Samstag
149447,2148102,10076484,True,2023-09-17,540,False,True,True,False,Sonntag
149707,2154198,10076484,True,2023-09-18,600,False,True,True,False,Montag
150029,2160327,10076484,True,2023-09-19,1440,False,True,True,False,Dienstag
150111,2162422,10076484,True,2023-09-20,1440,False,True,True,False,Mittwoch
150554,2170676,10076484,True,2023-09-21,1440,False,True,True,False,Donnerstag
150658,2173564,10076484,True,2023-09-22,480,False,True,True,False,Freitag
150904,2179704,10076484,True,2023-09-23,1440,False,True,True,False,Samstag
151152,2184868,10076484,True,2023-09-24,1440,False,True,True,False,Sonntag
151863,2199517,10076484,True,2023-09-25,1440,False,True,True,False,Montag
151864,2199520,10076484,True,2023-09-26,1440,False,True,True,False,Dienstag
151865,2199527,10076484,True,2023-09-27,720,False,True,True,False,Mittwoch
152416,2210991,10076484,True,2023-09-28,1440,False,True,True,False,Donnerstag
152417,2210993,10076484,True,2023-09-29,1440,False,True,True,False,Freitag
152418,2210994,10076484,True,2023-09-30,1440,False,True,True,False,Samstag
153350,2230874,10076484,True,2023-10-01,1440,False,True,True,False,Sonntag
153351,2230875,10076484,True,2023-10-02,1440,False,True,True,False,Montag
153352,2230877,10076484,True,2023-10-03,1440,False,True,True,False,Dienstag
153614,2236658,10076484,True,2023-10-04,1440,False,True,True,False,Mittwoch
153615,2236660,10076484,True,2023-10-05,1440,False,True,True,False,Donnerstag
154105,2246520,10076484,True,2023-10-06,960,False,True,True,False,Freitag
154366,2251634,10076484,True,2023-10-07,1440,False,True,True,False,Samstag
154633,2257540,10076484,True,2023-10-08,1440,False,True,True,False,Sonntag
155181,2270473,10076484,True,2023-10-10,1440,False,True,True,False,Dienstag
155458,2275934,10076484,True,2023-10-11,1440,False,True,True,False,Mittwoch
155844,2284119,10076484,True,2023-10-12,1440,False,True,True,False,Donnerstag
155845,2284124,10076484,True,2023-10-13,1440,False,True,True,False,Freitag
156112,2289624,10076484,True,2023-10-14,1440,False,True,True,False,Samstag
156768,2302986,10076484,True,2023-10-15,1200,False,True,True,False,Sonntag
156770,2303011,10076484,True,2023-10-16,1440,False,True,True,False,Montag
156771,2303023,10076484,True,2023-10-17,1440,False,True,True,False,Dienstag
157154,2311402,10076484,True,2023-10-18,1440,False,True,True,False,Mittwoch
157155,2311405,10076484,True,2023-10-19,1440,False,True,True,False,Donnerstag
157665,2322351,10076484,True,2023-10-20,1440,False,True,True,False,Freitag
157856,2326391,10076484,True,2023-10-21,1440,False,True,True,False,Samstag

In [27]:
req_df[req_df["patient_info_id"] == 94719087].sort_values("attack_time")

,id,patient_info_id,headache,attack_time,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,weekday
0,124,94719087,True,2020-06-25,360,False,True,True,False,Donnerstag
1,125,94719087,True,2020-06-26,180,False,True,True,False,Freitag
2,135,94719087,True,2020-06-27,240,False,True,True,False,Samstag
3,172,94719087,True,2020-06-29,120,False,True,False,False,Montag
4,186,94719087,True,2020-07-01,60,False,True,False,False,Mittwoch
...,...,...,...,...,...,...,...,...,...,...
152671,2216293,94719087,True,2023-09-27,120,False,True,False,True,Mittwoch
152672,2216294,94719087,True,2023-09-28,240,False,True,True,True,Donnerstag
153310,2230092,94719087,True,2023-10-01,180,False,True,False,True,Sonntag
153318,2230124,94719087,True,2023-10-02,120,False,True,False,True,Montag
156756,2302737,94719087,True,2023-10-17,180,True,False,False,True,Dienstag