In [11]:
import pandas as pd
import numpy as np
import matplotlib as mtl
import seaborn as sb

In [12]:
df = pd.read_csv("dataset/Attacks_V1_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)

In [13]:
df.shape

(996339, 52)

In [14]:
df.columns

Index(['id', 'headache', 'migraine', 'attack_time', 'intensity', 'duration',
       'symptoms_both_side_headache', 'symptoms_one_side_headache',
       'symptoms_pulsating_headache', 'symptoms_dull_headache',
       'symptoms_increased_during_physical_activity', 'symptoms_nausea',
       'symptoms_vomiting', 'symptoms_light_sensitivity',
       'symptoms_noise_sensitivity', 'symptoms_smell_sensitivity',
       'symptoms_vertigo', 'symptoms_concentration_disorder',
       'symptoms_tiredness', 'symptoms_aura', 'symptoms_aura_vision',
       'symptoms_aura_emotion', 'symptoms_aura_speech',
       'symptoms_aura_paralysis', 'effects_unfit_for_work',
       'effects_unfit_for_household_recreation', 'effects_doctor',
       'effects_emergency_room', 'effects_hospital', 'comment_menstruation',
       'patient_info_id', 'source_version_id', 'api_version_id', 'create_date',
       'modified_date', 'nMed', 'Triptane_Geb', 'Triptane_Eff',
       'EinfacheSM_Geb', 'EinfacheSM_Eff', 'Uebelkeit_Geb', 'Uebelkeit_Eff',
       'Opoide_Geb', 'Opoide_Eff', 'Kombi_Geb', 'Kombi_Eff',
       'DitaneGepante_Geb', 'DitaneGepante_Eff', 'Ergotamin_Geb',
       'Ergotamin_Eff', 'medication', 'weekday'],
      dtype='object')

In [15]:
df.head()

,id,headache,migraine,attack_time,intensity,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,...,Opoide_Geb,Opoide_Eff,Kombi_Geb,Kombi_Eff,DitaneGepante_Geb,DitaneGepante_Eff,Ergotamin_Geb,Ergotamin_Eff,medication,weekday
0,124,True,True,2020-06-25,8,360,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Donnerstag
1,125,True,True,2020-06-26,5,180,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Freitag
2,135,True,True,2020-06-27,3,240,False,True,True,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Samstag
3,172,True,True,2020-06-29,3,120,False,True,False,False,...,0.0,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Montag
4,179,True,False,2020-06-30,5,360,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Dienstag

In [29]:
df['duration'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 996339 entries, 0 to 996338
Series name: duration
Non-Null Count   Dtype
--------------   -----
996339 non-null  int64
dtypes: int64(1)
memory usage: 7.6 MB

In [17]:
relevant_columns=["id","headache","attack_time","duration","symptoms_both_side_headache", "symptoms_one_side_headache",
       "symptoms_pulsating_headache", "symptoms_dull_headache","weekday"]
req_df=df[relevant_columns]

In [24]:
req_df.head(40)

,id,headache,attack_time,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,weekday
0,124,True,2020-06-25,360,False,True,True,False,Donnerstag
1,125,True,2020-06-26,180,False,True,True,False,Freitag
2,135,True,2020-06-27,240,False,True,True,False,Samstag
3,172,True,2020-06-29,120,False,True,False,False,Montag
4,179,True,2020-06-30,360,False,False,False,False,Dienstag
5,186,True,2020-07-01,60,False,True,False,False,Mittwoch
6,189,True,2020-07-01,420,False,False,False,False,Mittwoch
7,194,True,2020-07-02,300,False,False,False,False,Donnerstag
8,199,True,2020-07-02,60,False,True,False,False,Donnerstag
9,215,True,2020-07-03,1440,False,False,False,False,Freitag
10,224,True,2020-07-04,300,False,True,True,False,Samstag
11,226,True,2020-07-04,1440,False,False,False,False,Samstag
12,235,True,2020-07-05,1440,False,False,False,False,Sonntag
13,242,True,2020-07-05,120,False,True,True,False,Sonntag
14,254,True,2020-06-22,960,False,False,False,False,Montag
15,260,True,2020-07-06,1440,False,False,False,False,Montag
16,272,True,2020-07-07,600,False,False,False,False,Dienstag
17,274,True,2020-07-07,120,False,True,True,False,Dienstag
18,278,True,2020-07-07,1020,False,False,False,False,Dienstag
19,279,True,2020-07-07,1440,False,False,False,False,Dienstag
20,291,True,2020-07-08,720,False,True,False,False,Mittwoch
21,315,True,2020-07-08,1440,False,False,False,False,Mittwoch
22,321,True,2020-07-09,840,False,False,False,False,Donnerstag
23,323,True,2020-07-08,1080,False,False,False,False,Mittwoch
24,328,True,2020-07-09,240,False,True,True,False,Donnerstag
25,330,True,2020-07-09,1440,False,False,False,False,Donnerstag
26,333,True,2020-07-09,480,False,True,True,False,Donnerstag
27,361,True,2020-07-08,360,False,True,False,False,Mittwoch
28,362,True,2020-07-09,300,False,True,False,False,Donnerstag
29,363,True,2020-07-10,240,False,True,False,False,Freitag
30,377,True,2020-07-10,480,False,True,False,False,Freitag
31,390,True,2020-07-11,120,False,True,True,False,Samstag
32,392,True,2020-07-10,1440,False,False,False,False,Freitag
33,393,True,2020-07-11,1440,False,False,False,False,Samstag
34,401,True,2020-07-12,120,False,True,False,False,Sonntag
35,403,True,2020-07-12,1440,False,False,False,False,Sonntag
36,408,True,2020-07-11,1080,False,False,False,False,Samstag
37,425,True,2020-07-07,540,False,True,False,False,Dienstag
38,426,True,2020-07-08,360,False,True,False,False,Mittwoch
39,427,True,2020-07-09,360,False,True,False,False,Donnerstag

In [31]:
# Count missing values in each column
print(req_df.isnull().sum())

id                             0
headache                       0
attack_time                    0
duration                       0
symptoms_both_side_headache    0
symptoms_one_side_headache     0
symptoms_pulsating_headache    0
symptoms_dull_headache         0
weekday                        0
dtype: int64

In [32]:
print(req_df.isna().any())

id                             False
headache                       False
attack_time                    False
duration                       False
symptoms_both_side_headache    False
symptoms_one_side_headache     False
symptoms_pulsating_headache    False
symptoms_dull_headache         False
weekday                        False
dtype: bool

In [33]:
#check the numeric columns for irregularity

# Convert to numeric, invalid entries become NaN
df["duration_check"] = pd.to_numeric(df["duration"], errors='coerce')

# Rows where conversion failed
invalid_rows = df[df["duration_check"].isna()]
print("Rows with invalid duration values:")
print(invalid_rows)

Rows with invalid duration values:
Empty DataFrame
Columns: [id, headache, migraine, attack_time, intensity, duration, symptoms_both_side_headache, symptoms_one_side_headache, symptoms_pulsating_headache, symptoms_dull_headache, symptoms_increased_during_physical_activity, symptoms_nausea, symptoms_vomiting, symptoms_light_sensitivity, symptoms_noise_sensitivity, symptoms_smell_sensitivity, symptoms_vertigo, symptoms_concentration_disorder, symptoms_tiredness, symptoms_aura, symptoms_aura_vision, symptoms_aura_emotion, symptoms_aura_speech, symptoms_aura_paralysis, effects_unfit_for_work, effects_unfit_for_household_recreation, effects_doctor, effects_emergency_room, effects_hospital, comment_menstruation, patient_info_id, source_version_id, api_version_id, create_date, modified_date, nMed, Triptane_Geb, Triptane_Eff, EinfacheSM_Geb, EinfacheSM_Eff, Uebelkeit_Geb, Uebelkeit_Eff, Opoide_Geb, Opoide_Eff, Kombi_Geb, Kombi_Eff, DitaneGepante_Geb, DitaneGepante_Eff, Ergotamin_Geb, Ergotamin_Eff, medication, weekday, duration_check]
Index: []

[0 rows x 53 columns]

In [34]:
invalid_weekday = df[~df["weekday"].apply(lambda x: isinstance(x, str))]
print("Rows with non-string weekday:")
print(invalid_weekday)

Rows with non-string weekday:
Empty DataFrame
Columns: [id, headache, migraine, attack_time, intensity, duration, symptoms_both_side_headache, symptoms_one_side_headache, symptoms_pulsating_headache, symptoms_dull_headache, symptoms_increased_during_physical_activity, symptoms_nausea, symptoms_vomiting, symptoms_light_sensitivity, symptoms_noise_sensitivity, symptoms_smell_sensitivity, symptoms_vertigo, symptoms_concentration_disorder, symptoms_tiredness, symptoms_aura, symptoms_aura_vision, symptoms_aura_emotion, symptoms_aura_speech, symptoms_aura_paralysis, effects_unfit_for_work, effects_unfit_for_household_recreation, effects_doctor, effects_emergency_room, effects_hospital, comment_menstruation, patient_info_id, source_version_id, api_version_id, create_date, modified_date, nMed, Triptane_Geb, Triptane_Eff, EinfacheSM_Geb, EinfacheSM_Eff, Uebelkeit_Geb, Uebelkeit_Eff, Opoide_Geb, Opoide_Eff, Kombi_Geb, Kombi_Eff, DitaneGepante_Geb, DitaneGepante_Eff, Ergotamin_Geb, Ergotamin_Eff, medication, weekday, duration_check]
Index: []

[0 rows x 53 columns]