In [1]:
import pandas as pd
import numpy as np
import matplotlib as mtl
import seaborn as sb
!pip install ydata-profiling

Looking in indexes: https://nexus.iisys.de/repository/ki-awz-pypi-group/simple, https://pypi.org/simple
Requirement already satisfied: ydata-profiling in /opt/conda/lib/python3.12/site-packages (4.18.3)
Requirement already satisfied: scipy<1.17,>=1.8 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (1.16.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (2.3.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (2.11.7)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /opt/conda/lib/python3.12/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (2.2.6)
Requirement already satisfied: minify-html>=0.15.0 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=4 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /opt/conda/lib/python3.12/site-packages (from ydata-profiling) (0.61.2)
Requirement already satisfied: PyWavelets in /opt/conda/lib/python3.12/site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /opt/conda/lib/python3.12/site-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /opt/conda/lib/python3.12/site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /opt/conda/lib/python3.12/site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.2)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3,>=2->ydata-profiling) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.8.3)
Requirement already satisfied: patsy>=0.5.6 in /opt/conda/lib/python3.12/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /opt/conda/lib/python3.12/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /opt/conda/lib/python3.12/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Requirement already satisfied: puremagic in /opt/conda/lib/python3.12/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [33]:
df1 = pd.read_csv("dataset/attack/Attacks_V1_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df2 = pd.read_csv("dataset/attack/Attacks_V2_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df3 = pd.read_csv("dataset/attack/Attacks_V3_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df4 = pd.read_csv("dataset/attack/Attacks_V4_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df5 = pd.read_csv("dataset/attack/Attacks_V5_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df6 = pd.read_csv("dataset/attack/Attacks_V6_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df7 = pd.read_csv("dataset/attack/Attacks_V7_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df8 = pd.read_csv("dataset/attack/Attacks_V8_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df9 = pd.read_csv("dataset/attack/Attacks_V9_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df10 = pd.read_csv("dataset/attack/Attacks_V10_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df11 = pd.read_csv("dataset/attack/Attacks_V11_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df12 = pd.read_csv("dataset/attack/Attacks_V12_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df13 = pd.read_csv("dataset/attack/Attacks_V13_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df14 = pd.read_csv("dataset/attack/Attacks_V14_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df15 = pd.read_csv("dataset/attack/Attacks_V15_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df16 = pd.read_csv("dataset/attack/Attacks_V16_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df17 = pd.read_csv("dataset/attack/Attacks_V17_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df18 = pd.read_csv("dataset/attack/Attacks_V18_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df19 = pd.read_csv("dataset/attack/Attacks_V19_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df20 = pd.read_csv("dataset/attack/Attacks_V20_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df21 = pd.read_csv("dataset/attack/Attacks_V21_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df22 = pd.read_csv("dataset/attack/Attacks_V22_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
df23 = pd.read_csv("dataset/attack/Attacks_V23_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)
#df_app= pd.read_csv("dataset/Attacks_AppOnly_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)

In [34]:
df1["visit"] = 1
df2["visit"] = 2
df3["visit"] = 3
df4["visit"] = 4
df5["visit"] = 5
df6["visit"] = 6
df7["visit"] = 7
df8["visit"] = 8
df9["visit"] = 9
df10["visit"] = 10
df12["visit"] = 11
df13["visit"] = 12
df14["visit"] = 13
df15["visit"] = 14
df16["visit"] = 15
df17["visit"] = 16
df17["visit"] = 17
df18["visit"] = 18
df19["visit"] = 19
df20["visit"] = 20
df21["visit"] = 21
df22["visit"] = 22
df23["visit"] = 23
#df_app["visit"] = 0

In [44]:
#ignore index(reorder the rows from 0 to n ) during concatenation
df_final = pd.concat([df1, df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22,df23],axis=0,ignore_index=True)

In [45]:
df_final = df_final.sort_values(["patient_info_id"])

In [46]:
df_final.shape

(4575646, 53)

In [47]:
df_final.head()

,id,headache,migraine,attack_time,intensity,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,...,Opoide_Eff,Kombi_Geb,Kombi_Eff,DitaneGepante_Geb,DitaneGepante_Eff,Ergotamin_Geb,Ergotamin_Eff,medication,weekday,visit
279640,1870355,True,False,2023-07-21,7,480,True,False,True,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Freitag,1.0
342378,2505321,True,True,2023-11-21,8,780,True,False,True,False,...,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Dienstag,1.0
340188,2483044,True,True,2023-11-18,10,960,True,False,True,False,...,"0,0",0.0,"0,00000000000000",0.0,0.0,0.0,"0,0",True,Samstag,1.0
524128,4700587,True,False,2024-09-08,6,360,False,True,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Sonntag,1.0
306407,2131030,True,False,2023-09-14,3,360,True,False,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Donnerstag,1.0

In [39]:
sample=df_final.sample(5000)

In [40]:
#data profiling
from ydata_profiling import ProfileReport
report = ProfileReport(sample, title="Post-Merge Profile", explorative=True)
report.to_file("profile_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 53/53 [00:00<00:00, 186491.70it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [48]:
relevant_columns=["id","patient_info_id","headache","attack_time","intensity","duration","symptoms_both_side_headache", "symptoms_one_side_headache",
       "symptoms_pulsating_headache", "symptoms_dull_headache","weekday","visit"]
req_df=df_final[relevant_columns]

In [51]:
#req_df.head(30)
req_df[1000:2000]

,id,patient_info_id,headache,attack_time,intensity,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,weekday,visit
1506229,10873540,10076484,True,2025-12-27,5,1440,False,True,True,False,Samstag,2.0
2390283,9368722,10076484,True,2025-09-22,6,1440,False,True,True,False,Montag,4.0
2700637,6138217,10076484,True,2025-01-27,9,1440,False,True,True,False,Montag,5.0
2749654,8482770,10076484,True,2025-07-25,3,1440,False,True,True,False,Freitag,5.0
1520226,11374700,10076484,True,2026-01-20,7,1440,False,True,True,False,Dienstag,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
952428,10982890,10076484,True,2025-12-29,8,1440,False,True,True,False,Montag,1.0
2705456,6338647,10076484,True,2025-02-13,8,1440,False,True,True,False,Donnerstag,5.0
768225,8077860,10076484,True,2025-06-15,6,1440,False,True,True,False,Sonntag,1.0
1500778,10682993,10076484,True,2025-12-12,6,1440,False,True,True,False,Freitag,2.0
466323,3958937,10076484,True,2024-06-13,8,1440,False,True,True,False,Donnerstag,1.0

In [43]:
req_df.duplicated().sum()

np.int64(0)

In [30]:
#req_df = req_df.set_index(["id"])
req_df.groupby(["patient_info_id"]).size().sort_values(ascending=False)

patient_info_id
45861150    1974
58668734    1937
25124162    1906
79404720    1837
78562347    1787
            ...
43054467       1
43051709       1
73254706       1
43179664       1
99963250       1
Length: 64212, dtype: int64

In [22]:
req_df.duplicated(subset=["patient_info_id", "attack_time"]).sum()

np.int64(0)

In [23]:
req_df = req_df.drop_duplicates(subset=["patient_info_id","attack_time","weekday"])
req_df.shape

(4066498, 11)

In [24]:
req_df.head(60)

,patient_info_id,headache,attack_time,intensity,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,weekday,visit
id,,,,,,,,,,,
117,72741515,True,2020-06-08,4,480,False,False,True,False,Montag,0.0
118,72741515,True,2020-06-09,5,360,False,False,True,False,Dienstag,0.0
124,94719087,True,2020-06-25,8,360,False,True,True,False,Donnerstag,1.0
125,94719087,True,2020-06-26,5,180,False,True,True,False,Freitag,1.0
127,44203359,True,2020-06-19,10,300,False,True,True,False,Freitag,0.0
128,44203359,True,2020-06-20,10,300,False,True,True,False,Samstag,0.0
129,44203359,True,2020-06-21,10,480,False,True,True,False,Sonntag,0.0
130,44203359,True,2020-06-22,6,180,False,True,True,False,Montag,0.0
131,44203359,True,2020-06-23,10,840,False,True,True,False,Dienstag,0.0
133,44203359,True,2020-06-24,1,1440,False,False,False,False,Mittwoch,0.0
134,44203359,True,2020-06-25,1,1440,False,False,False,False,Donnerstag,0.0
135,94719087,True,2020-06-27,3,240,False,True,True,False,Samstag,1.0
153,14736818,True,2020-06-28,7,300,False,False,True,False,Sonntag,0.0
154,14736818,True,2020-06-20,3,300,False,False,True,False,Samstag,0.0
155,14736818,True,2020-06-19,7,960,False,False,True,False,Freitag,0.0
156,14736818,True,2020-06-18,5,900,False,False,True,False,Donnerstag,0.0
157,14736818,True,2020-06-17,5,1080,False,False,True,False,Mittwoch,0.0
158,14736818,True,2020-06-16,6,1440,False,False,True,False,Dienstag,0.0
159,14736818,True,2020-06-15,6,1440,False,False,True,False,Montag,0.0
170,33315147,True,2020-06-29,1,60,False,False,True,False,Montag,0.0
172,94719087,True,2020-06-29,3,120,False,True,False,False,Montag,1.0
173,44203359,True,2020-06-29,5,540,False,False,False,False,Montag,0.0
175,44203359,True,2020-06-28,3,1440,False,False,False,False,Sonntag,0.0
176,33315147,True,2020-06-30,2,300,False,False,True,False,Dienstag,0.0
179,70854341,True,2020-06-30,5,360,False,False,False,False,Dienstag,1.0
186,94719087,True,2020-07-01,3,60,False,True,False,False,Mittwoch,1.0
189,70854341,True,2020-07-01,5,420,False,False,False,False,Mittwoch,1.0
191,44806461,True,2020-07-01,1,360,False,False,False,False,Mittwoch,0.0
193,33315147,True,2020-07-02,1,360,False,True,False,False,Donnerstag,0.0
194,70854341,True,2020-07-02,5,300,False,False,False,False,Donnerstag,1.0
195,65770551,True,2020-07-02,3,840,False,False,False,False,Donnerstag,0.0
199,94719087,True,2020-07-02,2,60,False,True,False,False,Donnerstag,1.0
200,44806461,True,2020-07-02,3,600,False,True,True,False,Donnerstag,0.0
214,43890977,True,2020-07-01,6,180,False,False,False,False,Mittwoch,0.0
215,70854341,True,2020-07-03,3,1440,False,False,False,False,Freitag,1.0
216,21100227,True,2020-06-30,1,180,False,False,True,False,Dienstag,0.0
217,21100227,True,2020-07-01,1,180,False,False,True,False,Mittwoch,0.0
218,21100227,True,2020-07-02,10,600,False,False,True,False,Donnerstag,0.0
223,82675674,True,2020-07-04,3,120,False,True,False,False,Samstag,0.0
224,94719087,True,2020-07-04,5,300,False,True,True,False,Samstag,1.0
226,70854341,True,2020-07-04,9,1440,False,False,False,False,Samstag,1.0
228,63970427,True,2020-07-03,10,1440,False,True,True,False,Freitag,0.0
229,63970427,True,2020-07-04,5,720,False,True,True,False,Samstag,0.0
230,63970427,True,2020-07-02,5,1440,False,True,True,False,Donnerstag,0.0
231,63970427,True,2020-06-24,6,900,False,True,False,False,Mittwoch,0.0
232,63970427,True,2020-06-25,6,900,False,True,False,False,Donnerstag,0.0
233,52418423,True,2020-07-04,8,540,False,True,False,False,Samstag,0.0
235,70854341,True,2020-07-05,9,1440,False,False,False,False,Sonntag,1.0
236,52418423,True,2020-07-05,3,240,False,True,False,False,Sonntag,0.0
242,94719087,True,2020-07-05,3,120,False,True,True,False,Sonntag,1.0
243,30344416,True,2020-07-05,8,1440,False,True,True,False,Sonntag,0.0
244,30344416,True,2020-07-04,6,1440,False,True,True,False,Samstag,0.0
245,30344416,True,2020-07-03,7,1440,False,True,True,False,Freitag,0.0
246,30344416,True,2020-07-02,9,1440,False,True,True,False,Donnerstag,0.0
254,40153165,True,2020-06-22,5,960,False,False,False,False,Montag,1.0
259,30344416,True,2020-07-06,9,1440,False,True,True,False,Montag,0.0
260,70854341,True,2020-07-06,5,1440,False,False,False,False,Montag,1.0
261,82675674,True,2020-07-06,1,120,False,False,True,False,Montag,0.0
269,33315147,True,2020-07-07,4,480,False,False,True,False,Dienstag,0.0
272,47912503,True,2020-07-07,0,600,False,False,False,False,Dienstag,1.0

In [16]:
req_df["visit"].value_counts()

visit
0.0    3070159
1.0     996339
Name: count, dtype: int64

In [17]:
#check if duplicated remains
req_df.duplicated(subset=["id","attack_time"]).sum()

np.int64(0)

In [25]:
req_df = req_df.set_index(["patient_info_id"])

In [26]:
req_df.head(60)

,headache,attack_time,intensity,duration,symptoms_both_side_headache,symptoms_one_side_headache,symptoms_pulsating_headache,symptoms_dull_headache,weekday,visit
patient_info_id,,,,,,,,,,
72741515,True,2020-06-08,4,480,False,False,True,False,Montag,0.0
72741515,True,2020-06-09,5,360,False,False,True,False,Dienstag,0.0
94719087,True,2020-06-25,8,360,False,True,True,False,Donnerstag,1.0
94719087,True,2020-06-26,5,180,False,True,True,False,Freitag,1.0
44203359,True,2020-06-19,10,300,False,True,True,False,Freitag,0.0
44203359,True,2020-06-20,10,300,False,True,True,False,Samstag,0.0
44203359,True,2020-06-21,10,480,False,True,True,False,Sonntag,0.0
44203359,True,2020-06-22,6,180,False,True,True,False,Montag,0.0
44203359,True,2020-06-23,10,840,False,True,True,False,Dienstag,0.0
44203359,True,2020-06-24,1,1440,False,False,False,False,Mittwoch,0.0
44203359,True,2020-06-25,1,1440,False,False,False,False,Donnerstag,0.0
94719087,True,2020-06-27,3,240,False,True,True,False,Samstag,1.0
14736818,True,2020-06-28,7,300,False,False,True,False,Sonntag,0.0
14736818,True,2020-06-20,3,300,False,False,True,False,Samstag,0.0
14736818,True,2020-06-19,7,960,False,False,True,False,Freitag,0.0
14736818,True,2020-06-18,5,900,False,False,True,False,Donnerstag,0.0
14736818,True,2020-06-17,5,1080,False,False,True,False,Mittwoch,0.0
14736818,True,2020-06-16,6,1440,False,False,True,False,Dienstag,0.0
14736818,True,2020-06-15,6,1440,False,False,True,False,Montag,0.0
33315147,True,2020-06-29,1,60,False,False,True,False,Montag,0.0
94719087,True,2020-06-29,3,120,False,True,False,False,Montag,1.0
44203359,True,2020-06-29,5,540,False,False,False,False,Montag,0.0
44203359,True,2020-06-28,3,1440,False,False,False,False,Sonntag,0.0
33315147,True,2020-06-30,2,300,False,False,True,False,Dienstag,0.0
70854341,True,2020-06-30,5,360,False,False,False,False,Dienstag,1.0
94719087,True,2020-07-01,3,60,False,True,False,False,Mittwoch,1.0
70854341,True,2020-07-01,5,420,False,False,False,False,Mittwoch,1.0
44806461,True,2020-07-01,1,360,False,False,False,False,Mittwoch,0.0
33315147,True,2020-07-02,1,360,False,True,False,False,Donnerstag,0.0
70854341,True,2020-07-02,5,300,False,False,False,False,Donnerstag,1.0
65770551,True,2020-07-02,3,840,False,False,False,False,Donnerstag,0.0
94719087,True,2020-07-02,2,60,False,True,False,False,Donnerstag,1.0
44806461,True,2020-07-02,3,600,False,True,True,False,Donnerstag,0.0
43890977,True,2020-07-01,6,180,False,False,False,False,Mittwoch,0.0
70854341,True,2020-07-03,3,1440,False,False,False,False,Freitag,1.0
21100227,True,2020-06-30,1,180,False,False,True,False,Dienstag,0.0
21100227,True,2020-07-01,1,180,False,False,True,False,Mittwoch,0.0
21100227,True,2020-07-02,10,600,False,False,True,False,Donnerstag,0.0
82675674,True,2020-07-04,3,120,False,True,False,False,Samstag,0.0
94719087,True,2020-07-04,5,300,False,True,True,False,Samstag,1.0
70854341,True,2020-07-04,9,1440,False,False,False,False,Samstag,1.0
63970427,True,2020-07-03,10,1440,False,True,True,False,Freitag,0.0
63970427,True,2020-07-04,5,720,False,True,True,False,Samstag,0.0
63970427,True,2020-07-02,5,1440,False,True,True,False,Donnerstag,0.0
63970427,True,2020-06-24,6,900,False,True,False,False,Mittwoch,0.0
63970427,True,2020-06-25,6,900,False,True,False,False,Donnerstag,0.0
52418423,True,2020-07-04,8,540,False,True,False,False,Samstag,0.0
70854341,True,2020-07-05,9,1440,False,False,False,False,Sonntag,1.0
52418423,True,2020-07-05,3,240,False,True,False,False,Sonntag,0.0
94719087,True,2020-07-05,3,120,False,True,True,False,Sonntag,1.0
30344416,True,2020-07-05,8,1440,False,True,True,False,Sonntag,0.0
30344416,True,2020-07-04,6,1440,False,True,True,False,Samstag,0.0
30344416,True,2020-07-03,7,1440,False,True,True,False,Freitag,0.0
30344416,True,2020-07-02,9,1440,False,True,True,False,Donnerstag,0.0
40153165,True,2020-06-22,5,960,False,False,False,False,Montag,1.0
30344416,True,2020-07-06,9,1440,False,True,True,False,Montag,0.0
70854341,True,2020-07-06,5,1440,False,False,False,False,Montag,1.0
82675674,True,2020-07-06,1,120,False,False,True,False,Montag,0.0
33315147,True,2020-07-07,4,480,False,False,True,False,Dienstag,0.0
47912503,True,2020-07-07,0,600,False,False,False,False,Dienstag,1.0