In [1]:
import pandas as pd
import numpy as np
import matplotlib as mtl
import seaborn as sb

In [2]:
df = pd.read_csv("dataset/Patients_V1_02-03-2026.csv", on_bad_lines='skip', sep=';', low_memory=False)

In [3]:
df.shape

(6631, 1356)

In [4]:
df.describe()

,number_in_K1,id_patient,birthyear,postal_code_K1,total_nr_cycles,nr_dc_before_K1,nr_pc_before_K1,ID_PC_K1,ID_DC_K1,id_center_K1,...,Fibromyalgie_K1,Bruxismus..Zähneknirschen._K1,Chronischer.Schmerz.bei.Arthrose...Knie_K1,Chronischer.Schmerz.bei.Arthrose...Hüfte_K1,Chronischer.Schmerz.bei.Arthrose...Finger_K1,Chronischer.Schmerz.bei.Arthrose...Andere_K1,Andere.Erkrankungen_K1,Operationen_K1,number_begleit_Medi_K1,age_reg
count,6631.000000,6.631000e+03,6631.000000,6631.000000,6631.000000,6631.0,6631.000000,6631.000000,6631.000000,6.631000e+03,...,6631.000000,6631.000000,6631.000000,6631.000000,6631.000000,6631.000000,6631.000000,6631.000000,6631.000000,6631.000000
mean,4849.043583,5.528867e+07,1984.585734,62.367818,3.254411,0.0,0.080682,22128.557080,22957.583773,3.774877e+07,...,0.024732,0.166189,0.024883,0.015081,0.019454,0.025637,0.343086,0.681496,1.080983,38.553763
std,2793.419302,2.595205e+07,13.647938,33.193086,3.464359,0.0,0.299783,14242.344898,14383.649687,2.304755e+07,...,0.155320,0.372278,0.155781,0.121883,0.138125,0.158062,0.873308,1.422366,1.730461,13.503011
min,1.000000,1.000752e+07,1935.000000,1.000000,1.000000,0.0,0.000000,101.000000,106.000000,1.625679e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.000000
25%,2465.500000,3.340759e+07,1974.000000,28.000000,1.000000,0.0,0.000000,8972.000000,9527.500000,1.625679e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,27.000000
50%,4868.000000,5.564993e+07,1986.000000,82.000000,2.000000,0.0,0.000000,21728.000000,22516.000000,3.420250e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,37.000000
75%,7279.000000,7.809693e+07,1996.000000,88.000000,4.000000,0.0,0.000000,34238.500000,35275.500000,4.597144e+07,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,49.000000
max,9667.000000,9.999193e+07,2009.000000,99.000000,26.000000,0.0,3.000000,49397.000000,49422.000000,9.887674e+07,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,19.000000,27.000000,29.000000,90.000000

In [5]:
df.head(12)

,export_date,number_in_K1,id_patient,date_registration,gender,birthyear,postal_code_K1,date_first_pc,date_first_dc,total_nr_cycles,...,Fibromyalgie_K1,Bruxismus..Zähneknirschen._K1,Chronischer.Schmerz.bei.Arthrose...Knie_K1,Chronischer.Schmerz.bei.Arthrose...Hüfte_K1,Chronischer.Schmerz.bei.Arthrose...Finger_K1,Chronischer.Schmerz.bei.Arthrose...Andere_K1,Andere.Erkrankungen_K1,Operationen_K1,number_begleit_Medi_K1,age_reg
0,2026-03-02,1,10007520,2023-06-22,weiblich,1962,67,2023-08-12,2023-08-21,1,...,0,0,0,0,0,0,0,0,1,61
1,2026-03-02,2,10022137,2021-10-24,männlich,1964,85,2021-10-24,2021-11-15,1,...,0,1,0,0,0,0,0,1,1,57
2,2026-03-02,6,10070992,2023-05-22,weiblich,1998,87,2025-07-28,2025-08-07,3,...,0,0,0,0,0,0,0,0,1,25
3,2026-03-02,7,10072456,2025-01-14,weiblich,2001,7,2025-01-14,2025-01-21,1,...,0,0,0,0,0,0,0,0,0,24
4,2026-03-02,8,10076150,2020-10-26,weiblich,2000,84,2021-01-07,2021-01-15,1,...,0,0,0,0,0,0,0,0,0,20
5,2026-03-02,9,10076484,2023-09-15,weiblich,1973,84,2023-09-15,2024-10-16,5,...,0,0,0,0,0,0,0,2,2,50
6,2026-03-02,12,10098623,2023-03-28,weiblich,1978,17,2023-03-28,2023-04-18,8,...,0,0,0,0,0,0,0,7,2,45
7,2026-03-02,13,10100880,2023-03-14,weiblich,1975,94,2023-05-09,2023-12-07,1,...,0,1,0,0,0,0,1,1,1,48
8,2026-03-02,15,10111638,2025-01-14,weiblich,1974,83,2025-04-15,2025-04-29,4,...,0,0,0,0,0,0,0,0,1,51
9,2026-03-02,16,10112389,2025-04-09,weiblich,1987,88,2025-04-13,2025-04-24,2,...,0,0,0,0,0,0,0,0,0,38
10,2026-03-02,17,10112458,2025-05-16,männlich,1978,86,2025-05-16,2025-06-23,1,...,0,0,0,0,0,1,1,1,3,47
11,2026-03-02,18,10125810,2025-05-13,weiblich,1975,6,2025-08-25,2025-12-29,2,...,0,0,0,0,0,0,1,0,4,50

In [6]:
df.tail(12)

,export_date,number_in_K1,id_patient,date_registration,gender,birthyear,postal_code_K1,date_first_pc,date_first_dc,total_nr_cycles,...,Fibromyalgie_K1,Bruxismus..Zähneknirschen._K1,Chronischer.Schmerz.bei.Arthrose...Knie_K1,Chronischer.Schmerz.bei.Arthrose...Hüfte_K1,Chronischer.Schmerz.bei.Arthrose...Finger_K1,Chronischer.Schmerz.bei.Arthrose...Andere_K1,Andere.Erkrankungen_K1,Operationen_K1,number_begleit_Medi_K1,age_reg
6619,2026-03-02,9652,99833852,2025-01-15,weiblich,2003,12,2025-01-29,2025-01-30,2,...,0,0,0,0,0,0,0,1,0,22
6620,2026-03-02,9653,99840155,2021-08-19,weiblich,1974,88,2021-08-19,2021-09-07,14,...,0,0,0,0,0,0,0,0,0,47
6621,2026-03-02,9654,99843590,2024-09-05,weiblich,1990,28,2024-09-05,2024-11-04,2,...,0,0,0,0,0,0,0,0,0,34
6622,2026-03-02,9655,99847050,2023-08-11,weiblich,1975,27,2023-10-10,2023-10-10,2,...,0,0,0,0,0,0,0,0,0,48
6623,2026-03-02,9657,99855848,2025-11-14,weiblich,1980,88,2025-11-14,2025-11-14,1,...,0,1,0,0,0,0,0,0,3,45
6624,2026-03-02,9658,99859866,2025-05-06,weiblich,1994,1,2025-05-13,2025-05-13,5,...,0,0,0,0,0,0,0,0,0,31
6625,2026-03-02,9659,99879224,2025-05-26,weiblich,1989,99,2025-08-17,2025-12-29,2,...,0,0,0,0,0,0,1,0,0,36
6626,2026-03-02,9660,99940176,2025-12-25,männlich,1987,88,2025-12-25,2026-01-07,1,...,0,0,0,0,0,0,0,0,0,38
6627,2026-03-02,9661,99946992,2021-08-10,männlich,1971,86,2021-09-27,2021-12-22,2,...,0,1,1,0,0,0,0,1,4,50
6628,2026-03-02,9662,99947460,2025-05-20,weiblich,1996,1,2025-12-08,2025-12-08,2,...,0,0,0,0,0,0,3,0,4,29
6629,2026-03-02,9665,99979901,2025-09-23,weiblich,1998,88,2025-09-23,2025-09-26,1,...,0,0,0,0,0,0,0,0,1,27
6630,2026-03-02,9667,99991933,2025-09-15,weiblich,1987,88,2025-09-16,2025-09-18,1,...,0,1,0,0,0,0,7,0,1,38

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6631 entries, 0 to 6630
Columns: 1356 entries, export_date to age_reg
dtypes: bool(13), float64(262), int64(660), object(421)
memory usage: 68.0+ MB

In [8]:
df.columns[:20]

Index(['export_date', 'number_in_K1', 'id_patient', 'date_registration',
       'gender', 'birthyear', 'postal_code_K1', 'date_first_pc',
       'date_first_dc', 'total_nr_cycles', 'nr_dc_before_K1',
       'nr_pc_before_K1', 'control_type_K1', 'ID_PC_K1', 'ID_DC_K1',
       'state_dc_K1', 'id_center_K1', 'date_pc_K1', 'date_dc_K1',
       'cluster_module_K1'],
      dtype='object')

In [24]:
print(len(df.columns))

1356